import type { User } from 'firebase/auth';
import { updateProfile } from 'firebase/auth';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { getLocalProfile, saveLocalProfile } from './local-profile-service';

export function EditProfileScreen({ onBack, user }: { onBack: () => void; user: User }) {
  const [name, setName] = useState(user.displayName || ''); const [location, setLocation] = useState(''); const [bio, setBio] = useState(''); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { getLocalProfile(user.uid).then((profile) => { if (profile) { setName(profile.displayName); setLocation(profile.location); setBio(profile.bio); } }).catch(() => undefined); }, [user.uid]);
  async function save() { if (name.trim().length < 2) { setMessage('Enter your name.'); return; } try { setSaving(true); await Promise.all([updateProfile(user, { displayName: name.trim() }), saveLocalProfile(user.uid, { displayName: name.trim(), location: location.trim(), bio: bio.trim() })]); setMessage('Profile saved.'); } catch { setMessage('Unable to save profile.'); } finally { setSaving(false); } }
  return <View style={styles.screen}><View style={styles.header}><Pressable hitSlop={10} onPress={onBack}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Edit Profile</Text><View style={styles.space} /></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.label}>Display name</Text><TextInput onChangeText={setName} style={styles.input} value={name} /><Text style={styles.label}>Location</Text><TextInput onChangeText={setLocation} placeholder="Area, City" placeholderTextColor="#999" style={styles.input} value={location} /><Text style={styles.label}>Bio</Text><TextInput maxLength={180} multiline onChangeText={setBio} placeholder="Tell others about yourself" placeholderTextColor="#999" style={styles.bio} textAlignVertical="top" value={bio} /><Text style={styles.count}>{bio.length}/180</Text>{message ? <Text style={styles.message}>{message}</Text> : null}<Pressable disabled={saving} onPress={save} style={[styles.save, saving && styles.disabled]}>{saving ? <ActivityIndicator color="#FFF" /> : <Text style={styles.saveText}>Save Profile</Text>}</Pressable></ScrollView></View>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#FFF' }, header: { height: 60, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 15, borderBottomWidth: 1, borderBottomColor: '#EEE' }, back: { color: '#333', fontSize: 34, lineHeight: 36 }, title: { color: '#222', fontSize: 19, fontWeight: '700' }, space: { width: 25 }, content: { padding: 18, paddingBottom: 30 }, label: { color: '#333', fontSize: 13, fontWeight: '700', marginBottom: 8 }, input: { height: 48, borderWidth: 1, borderColor: '#DDD', borderRadius: 10, color: '#222', fontSize: 14, paddingHorizontal: 13, marginBottom: 20 }, bio: { height: 110, borderWidth: 1, borderColor: '#DDD', borderRadius: 10, color: '#222', fontSize: 14, padding: 13 }, count: { color: '#999', fontSize: 10, textAlign: 'right', marginTop: 5 }, message: { color: '#555', fontSize: 12, textAlign: 'center', marginTop: 16 }, save: { height: 50, alignItems: 'center', justifyContent: 'center', borderRadius: 13, backgroundColor: '#F45100', marginTop: 18 }, saveText: { color: '#FFF', fontSize: 15, fontWeight: '800' }, disabled: { opacity: 0.6 } });
