import type { User } from 'firebase/auth';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { getVendorApplication, saveVendorApplication } from './local-vendor-service';

export function VendorOnboardingScreen({ onBack, user }: { onBack: () => void; user: User }) {
  const [businessName, setBusinessName] = useState(''); const [category, setCategory] = useState(''); const [location, setLocation] = useState(''); const [phone, setPhone] = useState(''); const [status, setStatus] = useState('');
  useEffect(() => { getVendorApplication(user.uid).then((application) => { if (application) { setBusinessName(application.businessName); setCategory(application.category); setLocation(application.location); setPhone(application.phone); setStatus('Application saved on this device.'); } }).catch(() => undefined); }, [user.uid]);
  async function submit() { if (!businessName.trim() || !category.trim() || !location.trim() || !phone.trim()) { setStatus('Complete all fields first.'); return; } await saveVendorApplication(user.uid, { businessName: businessName.trim(), category: category.trim(), location: location.trim(), phone: phone.trim(), status: 'pending' }); setStatus('Vendor application saved on this device.'); }
  return <View style={styles.screen}><View style={styles.header}><Pressable hitSlop={10} onPress={onBack}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Become a Vendor</Text><View style={styles.space} /></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.intro}>Set up your business profile to sell as a verified vendor.</Text>{[['Business name', businessName, setBusinessName, 'Shopicom Store'], ['Business category', category, setCategory, 'Electronics'], ['Business location', location, setLocation, 'Area, City'], ['Contact phone', phone, setPhone, '+233 24 000 0000']].map(([label, value, setter, placeholder]) => <View key={label as string}><Text style={styles.label}>{label as string}</Text><TextInput keyboardType={label === 'Contact phone' ? 'phone-pad' : 'default'} onChangeText={setter as (text: string) => void} placeholder={placeholder as string} placeholderTextColor="#999" style={styles.input} value={value as string} /></View>)}{status ? <Text style={styles.status}>{status}</Text> : null}<Pressable onPress={submit} style={styles.submit}><Text style={styles.submitText}>Submit Application</Text></Pressable></ScrollView></View>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#FFF' }, header: { height: 60, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 15, borderBottomWidth: 1, borderBottomColor: '#EEE' }, back: { color: '#333', fontSize: 34, lineHeight: 36 }, title: { color: '#222', fontSize: 19, fontWeight: '700' }, space: { width: 25 }, content: { padding: 18, paddingBottom: 30 }, intro: { color: '#666', fontSize: 13, lineHeight: 19, marginBottom: 22 }, label: { color: '#333', fontSize: 13, fontWeight: '700', marginBottom: 8 }, input: { height: 48, borderWidth: 1, borderColor: '#DDD', borderRadius: 10, color: '#222', fontSize: 14, paddingHorizontal: 13, marginBottom: 18 }, status: { color: '#555', fontSize: 12, textAlign: 'center', marginVertical: 12 }, submit: { height: 50, alignItems: 'center', justifyContent: 'center', borderRadius: 13, backgroundColor: '#F45100', marginTop: 5 }, submitText: { color: '#FFF', fontSize: 15, fontWeight: '800' } });
