import { useEffect, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { getFavoriteListings, type LocalListing } from './local-listing-service';
import { getCloudFavoriteListingIds, getCombinedListings } from './listing-service';

export function FavoritesScreen({ onBack, onOpenListing }: { onBack: () => void; onOpenListing: (listing: LocalListing) => void }) {
  const [listings, setListings] = useState<LocalListing[]>([]);
  useEffect(() => { Promise.all([getFavoriteListings(), getCloudFavoriteListingIds().catch((): string[] => [])]).then(async ([local, cloudIds]) => { const cloud = cloudIds.length ? (await getCombinedListings()).filter((item) => item.cloudId && cloudIds.includes(item.cloudId)) : []; const merged = [...local, ...cloud]; setListings(merged.filter((item, index, items) => items.findIndex((candidate) => candidate.id === item.id || (candidate.cloudId && cloudIds.includes(candidate.cloudId) && candidate.cloudId === item.cloudId)) === index)); }).catch(() => setListings([])); }, []);
  return <View style={styles.screen}><View style={styles.header}><Pressable hitSlop={10} onPress={onBack}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Favorites</Text><Text style={styles.heart}>♥</Text></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>{listings.map((listing) => <Pressable key={listing.id} onPress={() => onOpenListing(listing)} style={styles.card}><Image resizeMode="cover" source={{ uri: listing.imageUrls[0] }} style={styles.image} /><View style={styles.copy}><Text numberOfLines={1} style={styles.name}>{listing.title}</Text><Text style={styles.price}>GHS {listing.price}</Text><Text numberOfLines={1} style={styles.location}>⌖ {listing.location}</Text></View><Text style={styles.arrow}>›</Text></Pressable>)}{!listings.length ? <View style={styles.empty}><Text style={styles.emptyTitle}>No favorites yet</Text><Text style={styles.emptyCopy}>Tap the heart on a product to save it here.</Text></View> : null}</ScrollView></View>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#FFF' }, header: { height: 60, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15, borderBottomWidth: 1, borderBottomColor: '#EEE' }, back: { color: '#333', fontSize: 34, lineHeight: 36, marginRight: 10 }, title: { flex: 1, color: '#222', fontSize: 19, fontWeight: '700' }, heart: { color: '#F45100', fontSize: 21 }, content: { padding: 15, paddingBottom: 30 }, card: { minHeight: 88, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#EEE', paddingVertical: 9 }, image: { width: 72, height: 72, borderRadius: 10, backgroundColor: '#F7F7F7' }, copy: { flex: 1, marginLeft: 12 }, name: { color: '#222', fontSize: 14, fontWeight: '700' }, price: { color: '#F45100', fontSize: 14, fontWeight: '800', marginTop: 5 }, location: { color: '#777', fontSize: 11, marginTop: 5 }, arrow: { color: '#AAA', fontSize: 28 }, empty: { alignItems: 'center', paddingTop: 110 }, emptyTitle: { color: '#222', fontSize: 18, fontWeight: '700' }, emptyCopy: { color: '#777', fontSize: 12, marginTop: 7 } });
