import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { getLocalListings, type LocalListing } from '../listings/local-listing-service';

export function NotificationsScreen({ onBack, onOpenListing }: { onBack: () => void; onOpenListing: (listing: LocalListing) => void }) {
  const [listings, setListings] = useState<LocalListing[]>([]);
  useEffect(() => { getLocalListings().then(setListings).catch(() => setListings([])); }, []);
  return <View style={styles.screen}><View style={styles.header}><Pressable hitSlop={10} onPress={onBack}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Notifications</Text><Text style={styles.bell}>♢</Text></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>{listings.map((listing) => <Pressable key={listing.id} onPress={() => onOpenListing(listing)} style={styles.item}><View style={styles.dot} /><View style={styles.copy}><Text style={styles.itemTitle}>Your listing is active</Text><Text numberOfLines={2} style={styles.message}>{listing.title} is saved and visible in your local marketplace.</Text><Text style={styles.time}>{new Date(listing.createdAt).toLocaleDateString()}</Text></View><Text style={styles.arrow}>›</Text></Pressable>)}{!listings.length ? <View style={styles.empty}><Text style={styles.emptyTitle}>No notifications yet</Text><Text style={styles.emptyCopy}>Listing updates will appear here.</Text></View> : null}</ScrollView></View>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#FFF' }, header: { height: 60, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15, borderBottomWidth: 1, borderBottomColor: '#EEE' }, back: { color: '#333', fontSize: 34, lineHeight: 36, marginRight: 10 }, title: { flex: 1, color: '#222', fontSize: 19, fontWeight: '700' }, bell: { color: '#F45100', fontSize: 22 }, content: { paddingHorizontal: 15, paddingBottom: 30 }, item: { minHeight: 88, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#EEE', paddingVertical: 13 }, dot: { width: 9, height: 9, borderRadius: 5, backgroundColor: '#F45100', marginRight: 12 }, copy: { flex: 1 }, itemTitle: { color: '#222', fontSize: 14, fontWeight: '700' }, message: { color: '#666', fontSize: 12, lineHeight: 17, marginTop: 4 }, time: { color: '#999', fontSize: 10, marginTop: 5 }, arrow: { color: '#AAA', fontSize: 27, marginLeft: 8 }, empty: { alignItems: 'center', paddingTop: 120 }, emptyTitle: { color: '#222', fontSize: 18, fontWeight: '700' }, emptyCopy: { color: '#777', fontSize: 12, marginTop: 7 } });
